<?php
/**
 * OptiMonk plugin for Magento 1.7+
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * For a copy of the GNU General Public License, see <http://www.gnu.org/licenses/>.
 *
 * @package     Wse_OptiMonk
 * @copyright   Copyright (c) 2016 Webshop Marketing Kft (www.optimonk.com)
 * @license     https://www.gnu.org/licenses/gpl-3.0.html GNU GENERAL PUBLIC LICENSE (GPL 3.0)
 * @author      Tibor Berna
 */
?>
<?php if ($this->isEnabled()) : ?>
    <?php $cartProducts = $this->getProducts(); ?>
        var adapter = OptiMonk.Visitor.createAdapter();
        adapter.Cart.clear();
        <?php if(!empty($cartProducts)): ?>
            <?php foreach ($cartProducts as $sku => $productDetails) { ?>
                adapter.Cart.add(<?php echo json_encode($sku); ?>, <?php echo json_encode($productDetails); ?>);
            <?php } ?>
        <?php endif; ?>
<?php endif; ?>