<?php
/**
 * OptiMonk plugin for Magento 1.7+
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * For a copy of the GNU General Public License, see <http://www.gnu.org/licenses/>.
 *
 * @package     Wse_OptiMonk
 * @copyright   Copyright (c) 2016 Webshop Marketing Kft (www.optimonk.com)
 * @license     https://www.gnu.org/licenses/gpl-3.0.html GNU GENERAL PUBLIC LICENSE (GPL 3.0)
 * @author      Tibor Berna
 */
$moduleName = $this->getRequest()->getModuleName();
$controllerName = $this->getRequest()->getControllerName();
$actionName = $this->getRequest()->getActionName();
$route = $moduleName . '/' . $controllerName . '/' . $actionName;
?>
<?php if ($this->isEnabled()) : ?>
    <?php $this->addAttribute('pageType', $route); ?>
    <!-- OptiMonk Entry Code -->
    <script>
        document.querySelector('html').addEventListener('optimonk#ready', function () {
            var data = "url=" + encodeURIComponent(window.location.href) + "&referrer=" + encodeURIComponent(document.referrer);
            OptiMonk.ajax.post(data, "//" + window.location.host + "/optimonk/cart/index/", OptiMonk.addResponseToHead)
        });
        (function(e,a){
            var t,r=e.getElementsByTagName("head")[0],c=e.location.protocol;
            t=e.createElement("script");t.type="text/javascript";
            t.charset="utf-8";t.async=!0;t.defer=!0;
            t.src=c+"//front.optimonk.com/public/"+a+"/js/preload.js";r.appendChild(t);
        })(document,"<?php echo $this->getId(); ?>");

    </script>
<?php endif; ?>